models/OrgPic.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "org_pic".
 *
 * @property int $id_pic
 * @property int $organization_id
 * @property string $name
 * @property string $email
 * @property string $phone
 * @property resource $avatar
 * @property int $created_at
 * @property int $updated_at
 */
class OrgPic extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'org_pic';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['organization_id', 'name', 'email', 'phone', 'avatar', 'created_at', 'updated_at'], 'required'],
            [['organization_id', 'created_at', 'updated_at'], 'integer'],
            [['avatar'], 'string'],
            [['name'], 'string', 'max' => 128],
            [['phone'], 'string', 'max' => 13],
            [['email'], 'string', 'max' => 64],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_pic' => 'Id Pic',
            'organization_id' => 'Organization ID',
            'name' => 'Name',
            'email' => 'Email',
            'phone' => 'Phone',
            'avatar' => 'Avatar',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }
}

controllers/OrgOrganizationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrgOrganization;
use app\search\OrgOrganizationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * OrgOrganizationController implements the CRUD actions for OrgOrganization model.
 */
class OrgOrganizationController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrgOrganization models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrgOrganizationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OrgOrganization model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new OrgOrganization model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new OrgOrganization();
        $userId = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post())) {
            $dirTrash = Yii::getAlias('@webroot/trash');
            $dirSubTrash = Yii::getAlias('@webroot/trash/logo');

            if (!is_dir($dirTrash)) {
                mkdir(Yii::getAlias('@webroot/trash'));
                if (!is_dir($dirSubTrash)) {
                    mkdir(Yii::getAlias('@webroot/trash/logo'));
                }
            } else {
                if (!is_dir($dirSubTrash)) {
                    mkdir(Yii::getAlias('@webroot/trash/logo'));
                }
            }
            $model->logo = UploadedFile::getInstance($model, 'logo');
            if($model->logo){
                    $imgIdLogo = mt_rand(100000, 999999);
                    $nameLogo = 'Logo' . $imgIdLogo . '-' . $model->logo->baseName . '.' . $model->logo->extension;
                    $pathLogo = Yii::getAlias('@webroot/trash/logo/') . $nameLogo;
                    $model->logo->saveAs($pathLogo);
                    $model->logo = $nameLogo;
            }
            $model->name = $model->name;
            $model->phone = "'".$model->phone."'";
            $model->email = $model->email;
            $model->website = $model->website;
            $model->user_id = $userId;
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id_organization]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing OrgOrganization model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        $ac_id = $model->user_id;
        if($ac_id == Yii::$app->user->id){    
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id_organization]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }
    }

    /**
     * Deletes an existing OrgOrganization model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {        
        $organizationModel = OrgOrganization::find()->where(['id_organization' => $id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){    
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }
    }

    /**
     * Finds the OrgOrganization model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrgOrganization the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrgOrganization::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/OrgPicController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrgPic;
use app\search\OrgPicSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * OrgPicController implements the CRUD actions for OrgPic model.
 */
class OrgPicController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrgPic models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrgPicSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OrgPic model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }   
    }

    /**
     * Creates a new OrgPic model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new OrgPic();
       
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){    
            if ($model->load(Yii::$app->request->post())) {
                $dirSubTrash = Yii::getAlias('@webroot/trash/avatar');
                if (!is_dir($dirSubTrash)) {
                    mkdir(Yii::getAlias('@webroot/trash/avatar'));
                }
                $model->avatar = UploadedFile::getInstance($model, 'avatar');
                if($model->avatar){
                        $imgIdAvatar = mt_rand(100000, 999999);
                        $nameAvatar = 'Avatar' . $imgIdAvatar . '-' . $model->avatar->baseName . '.' . $model->avatar->extension;
                        $pathAvatar = Yii::getAlias('@webroot/trash/avatar/') . $nameAvatar;
                        $model->avatar->saveAs($pathAvatar);
                        $model->avatar = $nameAvatar;
                }
                $model->name = $model->name;
                $model->phone = $model->phone;
                $model->email = $model->email;
                $model->organization_id = $id;            
                $model->save(false);

                return $this->redirect(['view', 'id' => $model->id_pic]);
            }

            return $this->render('create', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }   
    }

    /**
     * Updates an existing OrgPic model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id_pic]);
            }
            
            return $this->render('update', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }            
    }

    /**
     * Deletes an existing OrgPic model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {      
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){    
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }
    }

    /**
     * Finds the OrgPic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrgPic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrgPic::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/org-pic/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\models\OrgPic */
/* @var $form yii\widgets\ActiveForm */

$org_id = Yii::$app->getRequest()->getQueryParam('id');
?>

<div class="org-pic-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput() ?>
    
    <?=
    $form->field($model, 'avatar')->widget(FileInput::classname(), [  
        'options' => [
            'multiple' => false,
            'accept' => 'img/*',
            'class' => 'optionvalue-img',
            'placeholder' => 'maximum size is 2 MB',            
        ],
        'pluginOptions' => [
            'allowedFileExtensions' => ['jpg', 'png', 'jpeg'],
            'maxFileSize' => 2048, 
            'layoutTemplates' => ['footer' => 'Maximum size is 2 MB'],
            'browseLabel' => 'Browse (2MB)',
            'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => false,
        ]
    ]);
    ?>

    <div class="form-group">
        <?php echo '<div class="text-right" style="margin-right: 18px">' . Html::resetButton('<i class="glyphicon glyphicon-refresh"></i> Reset', ['class' => 'btn btn-default']) . ' ' . Html::submitButton('<i class="glyphicon glyphicon-save"></i> Submit', ['class' => 'btn btn-primary', 'id' => 'btn-create-bp', 'value' => $org_id]) . '</div>';
        ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/org-pic/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\search\OrgPicSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="org-pic-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_pic') ?>

    <?= $form->field($model, 'organization_id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'avatar') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/org-pic/create.php
<?php

use yii\helpers\Html;
use app\models\OrgOrganization;

/* @var $this yii\web\View */
/* @var $model app\models\OrgPic */

$this->title = 'Create PIC';
$org_id = Yii::$app->getRequest()->getQueryParam('id');
$orgModel = OrgOrganization::find()->where(['id_organization' => $org_id])->one();
$org_name = $orgModel->name;

$this->params['breadcrumbs'][] = ['label' => $org_name, 'url' => ['/org-organization/view', 'id' => $org_id]];
?>
<div class="org-pic-create">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,        
    ]) ?>

</div>

views/org-pic/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\search\OrgPicSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'PICs';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="org-pic-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Create New', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php 
    echo GridView::widget([
        'filterModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'options' => ['style' => 'font-size:12px;'],
        'pjax' => true,
        'pjaxSettings' => [
            'neverTimeout' => true,
            'options' => [
                'id' => '-pjax',
                'enableReplaceState' => false,
                'enablePushState' => false,
            ],
        ],
        'striped' => true,
        'hover' => true,
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'tableOptions' => ['class' => 'table table-hover'],
        'resizableColumns' => true,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn',
                'header' => 'No',
                'options' => [
                    'width' => '10px',
                ],
            ],

            'organization_id',
            'name',
            'email',
            'phone',
            ['class' => 'yii\grid\ActionColumn'],
        ],   
        'toolbar' => [
            ['content' =>                
                  Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax' => 0, 'class' => 'btn btn-default', 'title' => Yii::t('app', 'Reset Grid')])
            ],
            '{toggleData}',
        ],
        'panel' => [
            'type' => GridView::TYPE_SUCCESS,
            'after' => '<em>* Atur lebar kolom dengan cara menarik garis tepi kolom.</em>',
            'heading' => '<i class="glyphicon glyphicon-align-left"></i>&nbsp;&nbsp;<b>PIC List</b>',
        ],
        'persistResize' => false,
        'toggleDataOptions' => ['minCount' => 10]
    ]); 
    ?>
</div>

views/org-pic/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OrgPic */

$orgModel = app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
$nama = $orgModel->name;
$this->title = 'Update PIC: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => $nama, 'url' => ['/org-organization/view', 'id' => $model->organization_id]];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id_pic]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="org-pic-update">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/org-pic/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;


/* @var $this yii\web\View */
/* @var $model app\models\OrgPic */

$this->title = $model->name;
$orgModel = app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
$user_id = $orgModel->user_id;

$orgModel = app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
$nama = $orgModel->name;
$this->params['breadcrumbs'][] = ['label' => $nama, 'url' => ['/org-organization/view', 'id' => $model->organization_id]];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id_pic]];
\yii\web\YiiAsset::register($this);
?>
<div class="org-pic-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php 
        $server = "http://" . $_SERVER['HTTP_HOST'];
        $projectname = Yii::getAlias('@web');
        $pathLogo  = Yii::getAlias('/trash/avatar/');
        $logoName = $model->avatar;
    ?>
    <p>
        <img src="<?php echo $server . $projectname . $pathLogo . $logoName ?>" width="170" height="200" alt="PIC-Avatar" align="center" class="company-logo">
    </p>
    
    <?php if($user_id == Yii::$app->user->id){ ?>
    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_pic], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_pic], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php } ?>

    <h3><?php echo 'PIC Profile' ?></h3>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [            
            [
                'attribute' => 'organization_id',
                'label' => 'Organization',
                'value' => function ($model) {
                    $orgModel = app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
                    $nama = $orgModel->name;
                    return ucfirst($nama);
                },
            ],
            'name',
            'email:email',
            'phone',
            'avatar',
        ],
    ]) ?>

</div>