models/OrgOrganization.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "org_organization".
 *
 * @property int $id_organization
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $website
 * @property resource $logo
 * @property int $created_at
 * @property int $updated_at
 * @property int $user_id
 */
class OrgOrganization extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'org_organization';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'phone', 'email', 'website', 'logo', 'created_at', 'updated_at'], 'required'],
            [['created_at', 'updated_at', 'user_id'], 'integer'],
            [['logo'], 'string'],
            [['name'], 'string', 'max' => 128],
            [['phone'], 'string', 'max' => 13],
            [['email', 'website'], 'string', 'max' => 64],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_organization' => 'Id Organization',
            'name' => 'Name',
            'phone' => 'Phone',
            'email' => 'Email',
            'website' => 'Website',
            'logo' => 'Logo',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'user_id' => 'Account Manager',
        ];
    }
}

controllers/OrgOrganizationController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrgOrganization;
use app\search\OrgOrganizationSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * OrgOrganizationController implements the CRUD actions for OrgOrganization model.
 */
class OrgOrganizationController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrgOrganization models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrgOrganizationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OrgOrganization model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new OrgOrganization model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new OrgOrganization();
        $userId = Yii::$app->user->id;

        if ($model->load(Yii::$app->request->post())) {
            $dirTrash = Yii::getAlias('@webroot/trash');
            $dirSubTrash = Yii::getAlias('@webroot/trash/logo');

            if (!is_dir($dirTrash)) {
                mkdir(Yii::getAlias('@webroot/trash'));
                if (!is_dir($dirSubTrash)) {
                    mkdir(Yii::getAlias('@webroot/trash/logo'));
                }
            } else {
                if (!is_dir($dirSubTrash)) {
                    mkdir(Yii::getAlias('@webroot/trash/logo'));
                }
            }
            $model->logo = UploadedFile::getInstance($model, 'logo');
            if($model->logo){
                    $imgIdLogo = mt_rand(100000, 999999);
                    $nameLogo = 'Logo' . $imgIdLogo . '-' . $model->logo->baseName . '.' . $model->logo->extension;
                    $pathLogo = Yii::getAlias('@webroot/trash/logo/') . $nameLogo;
                    $model->logo->saveAs($pathLogo);
                    $model->logo = $nameLogo;
            }
            $model->name = $model->name;
            $model->phone = "'".$model->phone."'";
            $model->email = $model->email;
            $model->website = $model->website;
            $model->user_id = $userId;
            $model->save(false);
            return $this->redirect(['view', 'id' => $model->id_organization]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing OrgOrganization model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        
        $ac_id = $model->user_id;
        if($ac_id == Yii::$app->user->id){    
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id_organization]);
            }

            return $this->render('update', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }
    }

    /**
     * Deletes an existing OrgOrganization model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {        
        $organizationModel = OrgOrganization::find()->where(['id_organization' => $id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){    
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }
    }

    /**
     * Finds the OrgOrganization model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrgOrganization the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrgOrganization::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/OrgPicController.php
<?php

namespace app\controllers;

use Yii;
use app\models\OrgPic;
use app\search\OrgPicSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;

/**
 * OrgPicController implements the CRUD actions for OrgPic model.
 */
class OrgPicController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all OrgPic models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OrgPicSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single OrgPic model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }   
    }

    /**
     * Creates a new OrgPic model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new OrgPic();
       
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){    
            if ($model->load(Yii::$app->request->post())) {
                $dirSubTrash = Yii::getAlias('@webroot/trash/avatar');
                if (!is_dir($dirSubTrash)) {
                    mkdir(Yii::getAlias('@webroot/trash/avatar'));
                }
                $model->avatar = UploadedFile::getInstance($model, 'avatar');
                if($model->avatar){
                        $imgIdAvatar = mt_rand(100000, 999999);
                        $nameAvatar = 'Avatar' . $imgIdAvatar . '-' . $model->avatar->baseName . '.' . $model->avatar->extension;
                        $pathAvatar = Yii::getAlias('@webroot/trash/avatar/') . $nameAvatar;
                        $model->avatar->saveAs($pathAvatar);
                        $model->avatar = $nameAvatar;
                }
                $model->name = $model->name;
                $model->phone = $model->phone;
                $model->email = $model->email;
                $model->organization_id = $id;            
                $model->save(false);

                return $this->redirect(['view', 'id' => $model->id_pic]);
            }

            return $this->render('create', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }   
    }

    /**
     * Updates an existing OrgPic model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $model->organization_id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id_pic]);
            }
            
            return $this->render('update', [
                'model' => $model,
            ]);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }            
    }

    /**
     * Deletes an existing OrgPic model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {      
        $organizationModel = \app\models\OrgOrganization::find()->where(['id_organization' => $id])->one();
        $ac_id = $organizationModel->user_id;
        if($ac_id == Yii::$app->user->id){    
            $this->findModel($id)->delete();
            return $this->redirect(['index']);
        } else {
            throw new \yii\web\ForbiddenHttpException(Yii::t('yii', 'You are not allowed to perform this action.'));
        }
    }

    /**
     * Finds the OrgPic model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return OrgPic the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = OrgPic::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/org-organization/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;

/* @var $this yii\web\View */
/* @var $model app\models\OrgOrganization */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="org-organization-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput() ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'website')->textInput(['maxlength' => true]) ?>

    <?=
    $form->field($model, 'logo')->widget(FileInput::classname(), [  
        'options' => [
            'multiple' => false,
            'accept' => 'img/*',
            'class' => 'optionvalue-img',
            'placeholder' => 'maximum size is 2 MB',            
        ],
        'pluginOptions' => [
            'allowedFileExtensions' => ['jpg', 'png', 'jpeg'],
            'maxFileSize' => 2048, 
            'layoutTemplates' => ['footer' => 'Maximum size is 2 MB'],
            'browseLabel' => 'Browse (2MB)',
            'showPreview' => true,
            'showCaption' => true,
            'showRemove' => true,
            'showUpload' => false,
        ]
    ]);
    ?>

    <div class="form-group">
        <?php echo '<div class="text-right" style="margin-right: 18px">' . Html::resetButton('<i class="glyphicon glyphicon-refresh"></i> Reset', ['class' => 'btn btn-default']) . ' ' . Html::submitButton('<i class="glyphicon glyphicon-save"></i> Submit', ['class' => 'btn btn-primary', 'id' => 'btn-create-bp']) . '</div>';
        ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/org-organization/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\search\OrgOrganizationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="org-organization-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_organization') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'phone') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'website') ?>

    <?php // echo $form->field($model, 'logo') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/org-organization/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OrgOrganization */

$this->title = 'Create Organization';
$this->params['breadcrumbs'][] = ['label' => 'Organization List', 'url' => ['index']];
?>
<div class="org-organization-create">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/org-organization/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\Url;


/* @var $this yii\web\View */
/* @var $searchModel app\search\OrgOrganizationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Organizations';
?>
<div class="org-organization-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('<i class="glyphicon glyphicon-plus"></i> Organization', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php 
    echo GridView::widget([
        'filterModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'options' => ['style' => 'font-size:12px;'],
        'pjax' => true,
        'pjaxSettings' => [
            'neverTimeout' => true,
            'options' => [
                'id' => '-pjax',
                'enableReplaceState' => false,
                'enablePushState' => false,
            ],
        ],
        'striped' => true,
        'hover' => true,
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'tableOptions' => ['class' => 'table table-hover'],
        'resizableColumns' => true,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn',
                'header' => 'No',
                'options' => [
                    'width' => '10px',
                ],
            ],
            [
                'attribute' => 'name',
                'format' => 'raw',
                'vAlign' => 'middle',
                'hAlign' => 'center',
                'width' => '748px'
            ],
            [
                'attribute' => 'user_id',
                'format' => 'raw',
                'value' => function ($data) {
                    $modelUser = dektrium\user\models\User::find()->where(['id' => $data->user_id])->one();
                    $nama = $modelUser->username;
                    return ucfirst($nama);
                },
                'vAlign' => 'middle',
                'hAlign' => 'center',
                'width' => '300px',
                'mergeHeader' => true
            ],
            ['class' => 'yii\grid\ActionColumn',
                'options' => [
                    'width' => 58
                ],
                'visibleButtons' => [
                    'update' => function ($model, $key, $index) {
                        return $model->user_id === \Yii::$app->user->id ? true : false;
                    },
                    'delete' => function ($model, $key, $index) {
                        return $model->user_id === \Yii::$app->user->id ? true : false;
                    }
                ]
            ],
        ],    
        'toolbar' => [
            ['content' =>                
                  Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax' => 0, 'class' => 'btn btn-default', 'title' => Yii::t('app', 'Reset Grid')])
            ],
            '{toggleData}',
        ],
        'panel' => [
            'type' => GridView::TYPE_SUCCESS,
            'after' => '<em>* Atur lebar kolom dengan cara menarik garis tepi kolom.</em>',
            'heading' => '<i class="glyphicon glyphicon-align-left"></i>&nbsp;&nbsp;<b>Organization List</b>',
        ],
        'persistResize' => false,
        'toggleDataOptions' => ['minCount' => 10]
    ]); 
    ?>
</div>

views/org-organization/pic-list.php
<?php
use yii\helpers\Html;
use yii\helpers\HtmlPurifier;
use kartik\grid\GridView;

?>
<div class="pic-list">    
    <?= HtmlPurifier::process($model->name) ?>    
</div>

views/org-organization/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\OrgOrganization */

$this->title = 'Update Organization: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Organizations', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id_organization]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="org-organization-update">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/org-organization/view.php
<?php

use yii\helpers\Html;
use kartik\detail\DetailView;
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;

/* @var $this yii\web\View */
/* @var $model app\models\OrgOrganization */

$this->title = $model->name;
$listTitle = 'PIC List';
$this->params['breadcrumbs'][] = ['label' => 'Organizations', 'url' => ['index']];
\yii\web\YiiAsset::register($this);
?>
<div class="org-organization-view">

    <h1><?= Html::encode($this->title) ?></h1>
      
    <?php 
        $server = "http://" . $_SERVER['HTTP_HOST'];
        $projectname = Yii::getAlias('@web');
        $pathLogo  = Yii::getAlias('/trash/logo/');
        $logoName = $model->logo;
    ?>
    <p>
        <img src="<?php echo $server . $projectname . $pathLogo . $logoName ?>" width="170" height="200" alt="Company-Logo" align="center" class="company-logo">
    </p>
         
    <?php if($model->user_id == Yii::$app->user->id){ ?>
        <p>
        <?= Html::a('Update', ['update', 'id' => $model->id_organization], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id_organization], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <?php } ?>    

    <h3><?php echo 'Company Profile' ?></h3>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'phone',
            'email:email',
            'website'
        ],
    ]) ?>
    
    
    <?php if($model->user_id == Yii::$app->user->id){ ?>
    <h3><?php echo $listTitle?></h3>
    
    <?php if($model->user_id == Yii::$app->user->id){ ?>
    <p>
        <?= Html::a('<i class="glyphicon glyphicon-plus"></i> <b>PIC</b>', ['/org-pic/create', 'id' => $model->id_organization], ['class' => 'btn btn-add-pic']) ?>
    </p>
    <?php } ?>    
    
    <?php    
    
    $searchModel = new app\search\OrgPicSearch();
    $dataProvider = new ActiveDataProvider([
        'query' => app\models\OrgPic::find()->where(['organization_id' => $model->id_organization]),
        'pagination' => [
            'pageSize' => 5,
        ],
    ]);
    
    echo GridView::widget([
        'filterModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'options' => ['style' => 'font-size:12px;'],
        'pjax' => true,
        'pjaxSettings' => [
            'neverTimeout' => true,
            'options' => [
                'id' => '-pjax',
                'enableReplaceState' => false,
                'enablePushState' => false,
            ],
        ],
        'striped' => true,
        'hover' => true,
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'tableOptions' => ['class' => 'table table-hover'],
        'resizableColumns' => true,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn',
                'header' => 'No',
                'options' => [
                    'width' => '10px',
                ],
            ],
            [
                'attribute' => 'name',
                'format' => 'raw',
                'vAlign' => 'middle',
                'hAlign' => 'center',
                'width' => '548px'
            ],
            [
                'attribute' => 'phone',
                'format' => 'raw',
                'vAlign' => 'middle',
                'hAlign' => 'center',
                'width' => '200px',
                'mergeHeader' => true
            ],
            [
                'attribute' => 'email',
                'format' => 'raw',
                'vAlign' => 'middle',
                'hAlign' => 'center',
                'width' => '300px',
                'mergeHeader' => true
            ],
            [
                'header' => 'Action',
                'class' => 'yii\grid\ActionColumn',
                'headerOptions' => ['width' => '65', 'align' => 'center'],
                'visibleButtons' => [
                    'view' => function ($model, $key, $index) {
                        $org_id = Yii::$app->getRequest()->getQueryParam('id');
                        $orgModel = app\models\OrgOrganization::find()->where(['id_organization' => $org_id])->one();
                        $user_id = $orgModel->user_id;
                        return $user_id === \Yii::$app->user->id ? true : false;
                    },
                    'update' => function ($model, $key, $index) {
                        $org_id = Yii::$app->getRequest()->getQueryParam('id');
                        $orgModel = app\models\OrgOrganization::find()->where(['id_organization' => $org_id])->one();
                        $user_id = $orgModel->user_id;
                        return $user_id === \Yii::$app->user->id ? true : false;
                    },
                    'delete' => function ($model, $key, $index) {
                        $org_id = Yii::$app->getRequest()->getQueryParam('id');
                        $orgModel = app\models\OrgOrganization::find()->where(['id_organization' => $org_id])->one();
                        $user_id = $orgModel->user_id;
                        return $user_id === \Yii::$app->user->id ? true : false;
                    }
                ],
                'template' => '{view}&nbsp;&nbsp;{update}&nbsp;&nbsp;{delete}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-eye-open"></i>', $url, [
                                    'title' => Yii::t('app', 'view'),
                                    'data-toggle' => "modal",
                                    'data-target' => "#myModal",
                                    'data-method' => 'post',
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-trash"></i>', $url, [
                                    'title' => Yii::t('app', 'delete'),
                                    'data-toggle' => "modal",
                                    'data-target' => "#myModal",
                                    'data-method' => 'post',
                        ]);
                    },
                    'update' => function ($url, $model) {
                        return Html::a('<i class="glyphicon glyphicon-edit"></i>', $url, [
                                    'title' => Yii::t('app', 'update'),
                                    'data-toggle' => "modal",
                                    'data-target' => "#myModal",
                                    'data-method' => 'post',
                        ]);
                    },
                ],
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action === 'view') {
                        $url = Url::toRoute(['/org-pic/view', 'id' => $model->organization_id], ['data-method' => 'post',]);
                        return $url;
                    } else if ($action === 'delete') {
                        $url = Url::toRoute(['/org-pic/delete', 'id' => $model->organization_id], ['data-method' => 'post',]);
                        return $url;
                    } else if ($action === 'update') {
                        $url = Url::toRoute(['/org-pic/update', 'id' => $model->organization_id], ['data-method' => 'post',]);
                        return $url;
                    }
                }
            ],
        ],  
        'persistResize' => false,
        'toggleDataOptions' => ['minCount' => 10]
    ]); 
    ?>   
    
    <?php } ?>
</div>